# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('act_id', models.IntegerField(primary_key=True, serialize=False)),
                ('act_type', models.CharField(choices=[('SB', 'Savings Bank Account'), ('CA', 'Current Account')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='bank',
            fields=[
                ('bank_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=20)),
                ('bank_city', models.CharField(max_length=30)),
                ('bank_ifsc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=20)),
                ('cust_balance', models.IntegerField()),
                ('cust_email', models.CharField(max_length=30)),
                ('cust_dob', models.DateField()),
                ('cust_address', models.TextField(max_length=50)),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankWebApp.account')),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_details', models.CharField(choices=[('CR.', 'Credit'), ('DB.', 'Debit')], default='DB.', max_length=3)),
                ('transaction_amount', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankWebApp.account')),
            ],
            options={
                'get_latest_by': 'updated',
            },
        ),
        migrations.CreateModel(
            name='userPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='bank_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankWebApp.bank'),
        ),
    ]
